from __future__ import annotations

from .obligations import evaluate_obligations
from .projector import TaskState


def render_card(state: TaskState) -> str:
    header = state.task_id or f"{state.record_id} (capture)"
    obligations = evaluate_obligations(state, target="completed")
    lines = [
        "<!-- AUTO-GENERATED by IDC from events.jsonl. Do not edit directly. -->",
        f"# {header}",
        "",
        "## Current State",
        "",
        f"- Lifecycle: `{state.lifecycle}`",
        f"- Outcome: `{state.outcome or 'open'}`",
        f"- Classifications: {', '.join(state.classifications) or 'unclassified'}",
        f"- Conditions: {', '.join(sorted(state.conditions)) or 'none'}",
        f"- Activities: {', '.join(state.activities) or 'none'}",
    ]
    if not state.task_id:
        capture_note = f"- Capture: `{state.capture_mode}`"
        if state.expires_at:
            capture_note += f" (expires {state.expires_at})"
        lines.append(capture_note)
    lines.extend(
        (
            "",
            "## Intent Translation",
            "",
            f"- Goal: {state.goal or state.summary}",
            f"- Explicit: {_join(state.explicit)}",
            f"- Repository facts: {_join(state.repository_facts)}",
            f"- Proposed defaults: {_join(state.proposed_defaults)}",
            f"- Open decisions: {_join(state.open_decisions)}",
            "",
            "## Scope And Acceptance",
            "",
            f"- Scope: {_join(state.scope)}",
        )
    )
    passing = {
        acceptance_id
        for evidence in state.evidence
        if evidence.get("result") == "pass"
        for acceptance_id in evidence.get("acceptance_ids", [])
    }
    for item in state.acceptance:
        acceptance_id = item.get("id", "unknown")
        marker = "x" if acceptance_id in passing else " "
        lines.append(f"- [{marker}] `{acceptance_id}` {item.get('statement', '')}")
    if not state.acceptance:
        lines.append("- Acceptance: not recorded")
    lines.extend(("", "## Impact", ""))
    for name, level in sorted(state.impacts.items()):
        lines.append(f"- {name}: `{level}`")
    if not state.impacts:
        lines.append("- Not assessed")
    lines.extend(("", "## Evidence", ""))
    for evidence in state.evidence:
        mapped = ", ".join(evidence.get("acceptance_ids", [])) or "unmapped"
        lines.append(
            f"- `{evidence.get('kind', 'claimed')}` / `{evidence.get('result', 'unknown')}` "
            f"/ {mapped}: {evidence.get('summary', '')}"
        )
    if not state.evidence:
        lines.append("- None")
    lines.extend(("", "## Outstanding Obligations", ""))
    for item in obligations.hard_blocks:
        lines.append(f"- [ ] {item}")
    if not obligations.hard_blocks:
        lines.append("- None")
    lines.extend(("", "## Event Log", ""))
    for event in state.events:
        lines.append(
            f"- `{event.get('timestamp')}` `{event.get('type')}` "
            f"({event.get('provenance', 'claimed')})"
        )
    return "\n".join(lines) + "\n"


def _join(values: list[str]) -> str:
    return "; ".join(values) if values else "none"
